services:
  db: 
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - portfolio-hub-backend

  redis:
    container_name: redis
    image: redis:7
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - portfolio-hub-backend
      
volumes:
  postgres_data:
  redis_data:

networks:
  portfolio-hub-backend: